apiVersion: v1
kind: Secret
metadata:
  name: azure-cr
  namespace: unir
data:
  docker-server: YWNyY2Fzb3ByYWN0aWNvZG9zLmF6dXJlY3IuaW8= 
  docker-username: YWRtaW4=
  docker-password: OGNjSktaMC95bmxOTW9kSTNNNWxCUXNieUJudE8zZTdEWFJUYW83cmM4K0FDUkN5bGdBSw== 
