  - name: Configuraciones en la VM de Azure
    hosts: vmazure
    become: true
    remote_user: admuser
    tasks:
    - name: Instalar podman
      package:
        name: "podman"
        state: present
    - name: Instalar git
      package:
        name: "git-all"
        state: present
    - name: Clonar el repositorio para crear la imagen de Podman
      git:
        repo: https://github.com/dsegui661/caso-practico-2.git
        dest: /opt/github
        clone: yes
        update: yes
    - name: "Descarla la imagen de alpine"
      shell: |
          podman pull alpine:3.17
#         cd /opt/github/resources/podman/imgweb
#         podman build --tag nginx:casopractico2 -f ./Containerfile

#    - name: Log into DockerHub
#      docker_login:
#        username: dseguiunir
#        password: segui661Unir


    - name: Build and push an image using username and password
      containers.podman.podman_image:
        name: nginx:casopractico2
        path: /opt/github/resources/podman/imgweb
        push: yes
        username: "acrCasoPracticoDos"
        password: "sMqHL3AQ9N02giS3dQ5cS4El4nzb+tuOZRXcV5qS6H+ACRAVr03s"
        push_args:
          dest: acrcasopracticodos.azurecr.io


    - name: Pull an image
      containers.podman.podman_image:
        name: acrcasopracticodos.azurecr.io/nginx:casopractico2
        username: "acrCasoPracticoDos"
        password: "sMqHL3AQ9N02giS3dQ5cS4El4nzb+tuOZRXcV5qS6H+ACRAVr03s"


    - name: Ejecuta contenedor
      containers.podman.podman_container:
        name: webunir
        image: nginx:casopractico2
        state: started
        detach: true
        exposed_ports:
          - 443
        ports:
          - 443:443




#    - name: Build a basic OCI image
#      containers.podman.podman_image:
#        name: nginx:casopractico2
#        path: /opt/github/resources/podman/imgweb

#    - name: Pull an image
#      containers.podman.podman_image:
#        name: httpd
#    - name: Copying file into home
#      copy:
#        src: /root/ws1/index.html
#        dest: /home
