  - name: Configuraciones en la VM de Azure
    hosts: vmazure
    become: true
    remote_user: admuser
    tasks:
    - name: Instalar podman
      package:
        name: "podman"
        state: present
    - name: Instalar git
      package:
        name: "git-all"
        state: present
    - name: Clonar el repositorio para crear la imagen de Podman
      git:
        repo: https://github.com/dsegui661/caso-practico-2.git
        dest: /opt/github
        clone: yes
        update: yes
#    - name: "Crea la imagen de nginx"
#      shell: |
#         cd /opt/github/resources/podman/imgweb
#         podman build --tag nginx:casopractico2 -f ./Containerfile

#   - name: Build and push an image using username and password
#     containers.podman.podman_image:
#       name: nginx:casopractico2
#       path: /opt/github/resources/podman/imgweb
#       push: yes
#       username: bugs
#       password: "{{ vault_registry_password }}"
#       push_args:
#         dest: quay.io/acme

    - name: Build a basic OCI image
      containers.podman.podman_image:
        name: nginx:casopractico2
        path: /opt/github/resources/podman/imgweb

#    - name: Pull an image
#      containers.podman.podman_image:
#        name: httpd
#    - name: Copying file into home
#      copy:
#        src: /root/ws1/index.html
#        dest: /home
