  - name: Configuraciones en la VM de Azure
    hosts: vmazure
    become: true
    remote_user: admuser
    tasks:
    - name: Instalar podman
      package:
        name: "podman"
        state: present
#    - name: Pull an image
#      containers.podman.podman_image:
#        name: httpd
#    - name: Copying file into home
#      copy:
#        src: /root/ws1/index.html
#        dest: /home