# ##########################################
#
#    Parte 2 - Automatizaciones en AKS
#
# #########################################

# NOTA: Previo a esta paso copiaremos el Kubeconfig generado
#       por terraform al crear el cluster a la carpeta 
#       /home/usuario/.kube/config para tener acceso al cluster

- name: Configuraciones de contenedores en AKS
  hosts: vmazure
  become: true
  remote_user: admuser
  tasks:
      - name: Create a directory if it does not exist
        ansible.builtin.file:
          path: /root/.kube
          state: directory
          mode: '0755'

      - name: Copy file with owner and permissions
        ansible.builtin.copy:
          src: /home/dsegui/caso-practico-2/terraform/kubeconfig
          dest: /root/.kube/config
          mode: '0644'


      - name: instalamos  pre-requisitos
        pip:
          name:
            - PyYAML
            - kubernetes 
            - jsonpath
        become: true

      - name: Creacion de un namespace
        kubernetes.core.k8s:
          name: unir
          api_version: v1
          kind: Namespace
          state: present

      - name: Haremos el despliege de los permisos para el deploy
        kubernetes.core.k8s:
          state: present
          src: ../resources/aks/rabac_jenkins.yml

      - name: Haremos el despliege del alamcenamiento persistente
        kubernetes.core.k8s:
          state: present
          src: ../resources/aks/store_jenkins.yml

      - name: Haremos el despliege de Jenkins
        kubernetes.core.k8s:
          state: present
          src: ../resources/aks/deploy_jenkins.yml

      - name: Creamos los servicios para el deploy de Jenkins
        kubernetes.core.k8s:
          state: present
          src: ../resources/aks/store_jenkins.yml
